version: '3.8'

services:
  backend-api:
    build: ./command-center/backend-api
    container_name: sentinel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./command-center/backend-api:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend-app:
    build: ./command-center/frontend-app
    container_name: sentinel-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./command-center/frontend-app:/app
    working_dir: /app
    command: npm run dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: sentinel-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
  
